name: Node Github CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and test
        run: |
          npm install --save --legacy-peer-deps
          npm run build
        env:
          CI: true

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/next-FE
            git pull origin develop
            curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
                    . ~/.nvm/nvm.sh
            nvm install 16
            node -v
            npm install --save --legacy-peer-deps
            npm run build
            pm2 stop next-fe
            pm2 delete next-fe
            pm2 save
            pm2 start npm --name "next-fe" --  start
